[build]
builder = "nixpacks"
buildCommand = "pip install -e ."
[variables]
NIXPACKS_PKGS = "postgresql postgresql-client libpq python3 gcc pkg-config"
[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug"
healthcheckPath = "/health"
healthcheckTimeout = 100
